/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrientacionRouteImport } from './routes/orientacion'
import { Route as OjosAbiertosRouteImport } from './routes/ojos-abiertos'
import { Route as NavegacionRouteImport } from './routes/navegacion'
import { Route as MapaRecorridoRouteImport } from './routes/mapa-recorrido'
import { Route as LugaresCercanosRouteImport } from './routes/lugares-cercanos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EmergenciaRouteImport } from './routes/emergencia'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecorridoIdRouteImport } from './routes/recorrido.$id'
import { Route as DetalleIdRouteImport } from './routes/detalle.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientacionRoute = OrientacionRouteImport.update({
  id: '/orientacion',
  path: '/orientacion',
  getParentRoute: () => rootRouteImport,
} as any)
const OjosAbiertosRoute = OjosAbiertosRouteImport.update({
  id: '/ojos-abiertos',
  path: '/ojos-abiertos',
  getParentRoute: () => rootRouteImport,
} as any)
const NavegacionRoute = NavegacionRouteImport.update({
  id: '/navegacion',
  path: '/navegacion',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRecorridoRoute = MapaRecorridoRouteImport.update({
  id: '/mapa-recorrido',
  path: '/mapa-recorrido',
  getParentRoute: () => rootRouteImport,
} as any)
const LugaresCercanosRoute = LugaresCercanosRouteImport.update({
  id: '/lugares-cercanos',
  path: '/lugares-cercanos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciaRoute = EmergenciaRouteImport.update({
  id: '/emergencia',
  path: '/emergencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecorridoIdRoute = RecorridoIdRouteImport.update({
  id: '/recorrido/$id',
  path: '/recorrido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DetalleIdRoute = DetalleIdRouteImport.update({
  id: '/detalle/$id',
  path: '/detalle/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/configuracion': typeof ConfiguracionRoute
  '/emergencia': typeof EmergenciaRoute
  '/explorar': typeof ExplorarRoute
  '/favoritos': typeof FavoritosRoute
  '/historial': typeof HistorialRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/lugares-cercanos': typeof LugaresCercanosRoute
  '/mapa-recorrido': typeof MapaRecorridoRoute
  '/navegacion': typeof NavegacionRoute
  '/ojos-abiertos': typeof OjosAbiertosRoute
  '/orientacion': typeof OrientacionRoute
  '/register': typeof RegisterRoute
  '/detalle/$id': typeof DetalleIdRoute
  '/recorrido/$id': typeof RecorridoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/configuracion': typeof ConfiguracionRoute
  '/emergencia': typeof EmergenciaRoute
  '/explorar': typeof ExplorarRoute
  '/favoritos': typeof FavoritosRoute
  '/historial': typeof HistorialRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/lugares-cercanos': typeof LugaresCercanosRoute
  '/mapa-recorrido': typeof MapaRecorridoRoute
  '/navegacion': typeof NavegacionRoute
  '/ojos-abiertos': typeof OjosAbiertosRoute
  '/orientacion': typeof OrientacionRoute
  '/register': typeof RegisterRoute
  '/detalle/$id': typeof DetalleIdRoute
  '/recorrido/$id': typeof RecorridoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/configuracion': typeof ConfiguracionRoute
  '/emergencia': typeof EmergenciaRoute
  '/explorar': typeof ExplorarRoute
  '/favoritos': typeof FavoritosRoute
  '/historial': typeof HistorialRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/lugares-cercanos': typeof LugaresCercanosRoute
  '/mapa-recorrido': typeof MapaRecorridoRoute
  '/navegacion': typeof NavegacionRoute
  '/ojos-abiertos': typeof OjosAbiertosRoute
  '/orientacion': typeof OrientacionRoute
  '/register': typeof RegisterRoute
  '/detalle/$id': typeof DetalleIdRoute
  '/recorrido/$id': typeof RecorridoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asistente'
    | '/configuracion'
    | '/emergencia'
    | '/explorar'
    | '/favoritos'
    | '/historial'
    | '/home'
    | '/login'
    | '/lugares-cercanos'
    | '/mapa-recorrido'
    | '/navegacion'
    | '/ojos-abiertos'
    | '/orientacion'
    | '/register'
    | '/detalle/$id'
    | '/recorrido/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asistente'
    | '/configuracion'
    | '/emergencia'
    | '/explorar'
    | '/favoritos'
    | '/historial'
    | '/home'
    | '/login'
    | '/lugares-cercanos'
    | '/mapa-recorrido'
    | '/navegacion'
    | '/ojos-abiertos'
    | '/orientacion'
    | '/register'
    | '/detalle/$id'
    | '/recorrido/$id'
  id:
    | '__root__'
    | '/'
    | '/asistente'
    | '/configuracion'
    | '/emergencia'
    | '/explorar'
    | '/favoritos'
    | '/historial'
    | '/home'
    | '/login'
    | '/lugares-cercanos'
    | '/mapa-recorrido'
    | '/navegacion'
    | '/ojos-abiertos'
    | '/orientacion'
    | '/register'
    | '/detalle/$id'
    | '/recorrido/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenteRoute: typeof AsistenteRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EmergenciaRoute: typeof EmergenciaRoute
  ExplorarRoute: typeof ExplorarRoute
  FavoritosRoute: typeof FavoritosRoute
  HistorialRoute: typeof HistorialRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  LugaresCercanosRoute: typeof LugaresCercanosRoute
  MapaRecorridoRoute: typeof MapaRecorridoRoute
  NavegacionRoute: typeof NavegacionRoute
  OjosAbiertosRoute: typeof OjosAbiertosRoute
  OrientacionRoute: typeof OrientacionRoute
  RegisterRoute: typeof RegisterRoute
  DetalleIdRoute: typeof DetalleIdRoute
  RecorridoIdRoute: typeof RecorridoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientacion': {
      id: '/orientacion'
      path: '/orientacion'
      fullPath: '/orientacion'
      preLoaderRoute: typeof OrientacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ojos-abiertos': {
      id: '/ojos-abiertos'
      path: '/ojos-abiertos'
      fullPath: '/ojos-abiertos'
      preLoaderRoute: typeof OjosAbiertosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navegacion': {
      id: '/navegacion'
      path: '/navegacion'
      fullPath: '/navegacion'
      preLoaderRoute: typeof NavegacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-recorrido': {
      id: '/mapa-recorrido'
      path: '/mapa-recorrido'
      fullPath: '/mapa-recorrido'
      preLoaderRoute: typeof MapaRecorridoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lugares-cercanos': {
      id: '/lugares-cercanos'
      path: '/lugares-cercanos'
      fullPath: '/lugares-cercanos'
      preLoaderRoute: typeof LugaresCercanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencia': {
      id: '/emergencia'
      path: '/emergencia'
      fullPath: '/emergencia'
      preLoaderRoute: typeof EmergenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorrido/$id': {
      id: '/recorrido/$id'
      path: '/recorrido/$id'
      fullPath: '/recorrido/$id'
      preLoaderRoute: typeof RecorridoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detalle/$id': {
      id: '/detalle/$id'
      path: '/detalle/$id'
      fullPath: '/detalle/$id'
      preLoaderRoute: typeof DetalleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenteRoute: AsistenteRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EmergenciaRoute: EmergenciaRoute,
  ExplorarRoute: ExplorarRoute,
  FavoritosRoute: FavoritosRoute,
  HistorialRoute: HistorialRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  LugaresCercanosRoute: LugaresCercanosRoute,
  MapaRecorridoRoute: MapaRecorridoRoute,
  NavegacionRoute: NavegacionRoute,
  OjosAbiertosRoute: OjosAbiertosRoute,
  OrientacionRoute: OrientacionRoute,
  RegisterRoute: RegisterRoute,
  DetalleIdRoute: DetalleIdRoute,
  RecorridoIdRoute: RecorridoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
